### ISSUE TITLE
Pydio 6.2 getting into Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by heutger** [pydio/pydio-core#1003]
I once tried to update Pydio 6.0.8 (fresh installation) to Pydio 6.2, but after that Pydio was completely broken, so I reinstalled a fresh version of 6.2.

However I still get:

Warning: Invalid argument supplied for foreach() in /var/www/vhosts/heutger.net/t.heutger.net/conf/bootstrap_context.php on line 147

Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/heutger.net/t.heutger.net/conf/bootstrap_context.php:147) in /var/www/vhosts/heutger.net/t.heutger.net/index.php on line 40

Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/heutger.net/t.heutger.net/conf/bootstrap_context.php:147) in /var/www/vhosts/heutger.net/t.heutger.net/index.php on line 41

Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/heutger.net/t.heutger.net/conf/bootstrap_context.php:147) in /var/www/vhosts/heutger.net/t.heutger.net/index.php on line 42

Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/heutger.net/t.heutger.net/conf/bootstrap_context.php:147) in /var/www/vhosts/heutger.net/t.heutger.net/index.php on line 43
Invalid argument supplied for foreach()

(t.heutger.net is for temporary testing)

After reloading the page I get:

<tree>
<message type="ERROR">Invalid argument supplied for foreach()</message>
</tree>

I can reproduce by

rm data/cache/plugins_bootstrap.php

I have no glue (as it's a fresh install) what the issue can be. I read something about the mail handler, but either I choose one or I leave the setting with "No, can be adjusted later", I still get in trouble.

I tried to use the forum, but it seems, that it does not work. Logging in results in not been logged in, the URL also containts logout=0. The password reset link is also not working. Seems there are issues with moving from pyd.io to pydio.com.

**Comment by cdujeu** [comment]
hi @heutger 
Can you try to replace the foreach() loop by the following code?
```php
    if($boots !== false){
        foreach($boots as $b){
            $content .= 'require_once("'.$b.'");'."\n";
        }
    }
```
You may have to do the same in conf/bootstrap_repositories.php

About the forum, did you try to register on that page ? https://pydio.com/en/user/register

charles

**Comment by cdujeu** [comment]
Fixed in trunk

**Comment by heutger** [comment]
Seems to work now, many thanks. I believe will be included in 6.2.1 also, once released?

About the forum, no, it was a different login (https://pydio.com/forum/wp-login.php, seems to be a Wordpress login to the forum), my credentials also did not work at the login you provided above. I now tried to register there and still await the instructions to get signed up. Forum still does not work to login, I still get accepted with the right credentials and rejected with the wrong ones, but although accepted, I'm still as logged out again.

Just two other topics:

1. Can I run Pydio with an active HTTP Auth (by the web server) or will there be problems if using the update mechanism inside Pydio (will it call scripts on the installation which would require server based authentication, which will break the update procedure)? As I had issues updating 6.0.8 to 6.2 crashing my installation, maybe that was an issue there.

2. Although choosing mail as Mailer option in setup (either 6.0.8 or 6.2) lateron in the Mailer settings sendmail is taken and a sendmail path is given (not entered anywhere) as well as the sender address and name is empty (although given with the installation)?

Thanks,
Christian

**Comment by cdujeu** [comment]
Did you make sure to check your SPAM folder? We've tested the registration many times (on the "top" site, not via wordpress).

**Comment by cdujeu** [comment]
i'd like to fix the forum problem before starting q&a sessions :-)

**Comment by heutger** [comment]
Hi,

I just checked again, got no mail yet, also not in SPAM. I now tried to resent the instructions mail.

Regards,
Christian

**Comment by heutger** [comment]
Hi,

I also did not got the resent mail. There is also nothing in SPAM. My spam filters reject also some kind of SPAM based on blacklists, that can be the only issue, but I wonder then, why your mail should be blacklisted.

Regards,
Christian

**Comment by cdujeu** [comment]
can you send me the email with wich you tried to create an account? I can activate it manually. Send to team (at) pyd (dot) io.
-c

**Comment by heutger** [comment]
Hi,

would be happy, if you could followup the last open Q&A. Many thanks!

Regards,
Christian

**Comment by cdujeu** [comment]
did you post your questions in the forum finally? Sorry very busy...

**Comment by heutger** [comment]
Not yet, I hoped, as they are just quick short questions, to get a faster response here. I will use the forum next time for sure.

**Comment by heutger** [comment]
I posted into the forum on 14th of December, but still no answer neither here nor via forum? May you help out? Many thanks!

**Comment by cdujeu** [comment]
Can you point to your forum threads ?

**Comment by heutger** [comment]
https://pydio.com/forum/f/topic/http-auth-and-mailer-settings-questions/
